name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PowerShell
      uses: actions/setup-powershell@v2
    - name: Run Tests
      run: pwsh -File tests/Test-SplitVersion.ps1