name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PowerShell
      uses: actions/setup-powershell@v2
    - name: Install Pester
      run: Install-Module -Name Pester -Force -SkipPublisherCheck
    - name: Run Pester Tests
      run: |
        Invoke-Pester -Script tests/Test-SplitVersion.Tests.ps1 -Output Detailed