name: CI

on: [push, pull_request]

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Perform a Pester test
        shell: pwsh
        run: |
          Invoke-Pester -Script tests/Test-ChocoUpgrade.Tests.ps1 -Output Detailed
